import { type NextPage } from "next";
import Head from "next/head";
import { Header } from "../../components/Header";

const Resources: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dashboard - Theo&apos;s Typesafe Cult</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <header className="container">
          <Header />
        </header>
        <main className="container flex flex-col items-center justify-center gap-12 px-4 py-16 text-2xl text-white">
          Resources
        </main>
      </div>
    </>
  );
};

export default Resources;
