import { GetServerSideProps, type NextPage } from 'next';
import { unstable_getServerSession as getServerSession } from 'next-auth';
import { authOptions } from '../api/auth/[...nextauth]';
import Head from 'next/head';
import { useHydratedSession } from '@utils/customHooks';
import { NextPageWithLayout } from '../_app';
import { PageLayout } from '@components/PageLayout';
import { api } from '@utils/api';
import dayjs from 'dayjs';
import Title from '@components/ui/Title';

const Warnings: NextPageWithLayout = () => {
  const session = useHydratedSession();

  const warnings = api.warnings.getAllWarnings.useQuery();

  console.log('warnings', warnings.data);

  return (
    <>
      <Head>
        <title>Dashboard - Theo&apos;s Typesafe Cult</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-row items-baseline">
          <div className="grow">
            <Title type="h1">Warnings</Title>
          </div>
          <div className="">
            <form>
              <input
                className="rounded p-1"
                type="text"
                placeholder="Search (wip)"
              />
            </form>
          </div>
        </div>
        <div className="p-8 drop-shadow-lg">
          <div className="mt-10">
            <div className="flex flex-row">
              <div className="w-36">User</div>
              <div className="w-36">Admin</div>
              <div className="grow">Reason</div>
              <div className="w-36">Date</div>
            </div>

            {warnings?.data?.map((warning, index) => {
              //   const admin = api.warnings.getAdminName.useQuery({
              //     id: warning.adminId,
              //   });
              return (
                <div className="my-2 flex flex-row" key={warning.id}>
                  <div className="w-36 text-sm">{warning.user.name}</div>
                  <div className="w-36 text-sm">{warning.adminId}</div>
                  <div className="grow text-sm">{warning.reason}</div>
                  <div className="w-36 text-sm">
                    {dayjs(new Date(warning.dateAdded)).format('MMM D, YYYY')}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
};

Warnings.getLayout = function getLayout(page: React.ReactElement) {
  return (
    <>
      <PageLayout>{page}</PageLayout>
    </>
  );
};

export default Warnings;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerSession(context.req, context.res, authOptions);

  if (!session) {
    return {
      redirect: {
        permanent: false,
        destination: `/`,
      },
    };
  }
  return {
    props: {
      session: session,
    },
  };
};
