import { type NextPage } from 'next';
import Head from 'next/head';
import { signIn, signOut, useSession } from 'next-auth/react';

import { api } from '@utils/api';
import { Authbutton } from '../components/AuthButton';
import Link from 'next/link';

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Theo&apos;s Typesafe Cult</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Theo&apos;s Typesafe Cult
          </h1>
          <div className="flex flex-col items-center gap-2 text-2xl text-white">
            <p>
              If you don&apos;t know what this then there is no point logging
              in.
            </p>
          </div>
          <div className="flex flex-col items-center gap-2">
            <div className="flex flex-row gap-8 text-xl text-white">
              {sessionData && (
                <Link
                  href="/dashboard"
                  className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                >
                  Dashboard
                </Link>
              )}
              <Authbutton />
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
